<?php

namespace AppBundle\Repository;

/**
 * BoissonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoissonRepository extends \Doctrine\ORM\EntityRepository
{
}
